INSERT INTO Author (FirstName, LastName) VALUES ('Harper', 'Lee');
INSERT INTO Author (FirstName, LastName) VALUES ('George', 'Orwell');
INSERT INTO Author (FirstName, LastName) VALUES ('Jane', 'Austen');
INSERT INTO Author (FirstName, LastName) VALUES ('F. Scott', 'Fitzgerald');
INSERT INTO Author (FirstName, LastName) VALUES ('Herman', 'Melville');
INSERT INTO Author (FirstName, LastName) VALUES ('Leo', 'Tolstoy');
INSERT INTO Author (FirstName, LastName) VALUES ('J.R.R.', 'Tolkien');
INSERT INTO Author (FirstName, LastName) VALUES ('J.K.', 'Rowling');
INSERT INTO Author (FirstName, LastName) VALUES ('Dan', 'Brown');
INSERT INTO Author (FirstName, LastName) VALUES ('Stieg', 'Larsson');
INSERT INTO Author (FirstName, LastName) VALUES ('Neil', 'Gaiman');
INSERT INTO Author (FirstName, LastName) VALUES ('Terry', 'Pratchett');
INSERT INTO Author (FirstName, LastName) VALUES ('Stephen', 'King');
INSERT INTO Author (FirstName, LastName) VALUES ('Peter', 'Straub');
INSERT INTO Author (FirstName, LastName) VALUES ('George R.R.', 'Martin');
INSERT INTO Author (FirstName, LastName) VALUES ('John', 'Green');
INSERT INTO Author (FirstName, LastName) VALUES ('Khaled', 'Hosseini');
INSERT INTO Author (FirstName, LastName) VALUES ('Markus', 'Zusak');
INSERT INTO Author (FirstName, LastName) VALUES ('Gillian', 'Flynn');
INSERT INTO Author (FirstName, LastName) VALUES ('Suzanne', 'Collins');
INSERT INTO Author (FirstName, LastName) VALUES ('C.S.', 'Lewis');
INSERT INTO Author (FirstName, LastName) VALUES ('Paula', 'Hawkins');
INSERT INTO Author (FirstName, LastName) VALUES ('J.D.', 'Salinger');
INSERT INTO Author (FirstName, LastName) VALUES ('Aldous', 'Huxley');
INSERT INTO Author (FirstName, LastName) VALUES ('Mary', 'Shelley');
INSERT INTO Genre (Name) VALUES ('Science Fiction');
INSERT INTO Genre (Name) VALUES ('Fantasy');
INSERT INTO Genre (Name) VALUES ('Mystery');
INSERT INTO Genre (Name) VALUES ('Thriller');
INSERT INTO Genre (Name) VALUES ('Romance');
INSERT INTO Genre (Name) VALUES ('Western');
INSERT INTO Genre (Name) VALUES ('Dystopian');
INSERT INTO Genre (Name) VALUES ('Contemporary');
INSERT INTO Genre (Name) VALUES ('Historical');
INSERT INTO Genre (Name) VALUES ('Horror');
INSERT INTO Genre (Name) VALUES ('Literary Fiction');
INSERT INTO Genre (Name) VALUES ('Memoir');
INSERT INTO Genre (Name) VALUES ('Biography');
INSERT INTO Genre (Name) VALUES ('Self-Help');
INSERT INTO Genre (Name) VALUES ('Cookbook');
INSERT INTO Genre (Name) VALUES ('Art');
INSERT INTO Genre (Name) VALUES ('Poetry');
INSERT INTO Genre (Name) VALUES ('Travel');
INSERT INTO Genre (Name) VALUES ('Children');
INSERT INTO Genre (Name) VALUES ('Young Adult');
INSERT INTO Genre (Name) VALUES ('Graphic Novel');
INSERT INTO Genre (Name) VALUES ('True Crime');
INSERT INTO Genre (Name) VALUES ('Philosophy');
INSERT INTO Genre (Name) VALUES ('Psychology');
INSERT INTO Genre (Name) VALUES ('Science');
INSERT INTO Genre (Name) VALUES ('Religion');
INSERT INTO Genre (Name) VALUES ('Health');
INSERT INTO Genre (Name) VALUES ('Business');
INSERT INTO Genre (Name) VALUES ('Politics');
INSERT INTO Genre (Name) VALUES ('Education');
INSERT INTO Publisher (Name, Address) VALUES ('Green Works', '532 Chestnut St');
INSERT INTO Publisher (Name, Address) VALUES ('Golden House', '939 Elm St');
INSERT INTO Publisher (Name, Address) VALUES ('Blue Pages', '186 Cherry St');
INSERT INTO Publisher (Name, Address) VALUES ('Bright Media', '447 Chestnut St');
INSERT INTO Publisher (Name, Address) VALUES ('Prime House', '993 Oak St');
INSERT INTO Publisher (Name, Address) VALUES ('Global Press', '482 Birch St');
INSERT INTO Publisher (Name, Address) VALUES ('Bright Press', '419 Birch St');
INSERT INTO Publisher (Name, Address) VALUES ('Prime Books', '329 Oak St');
INSERT INTO Publisher (Name, Address) VALUES ('Sun Works', '879 Pine St');
INSERT INTO Publisher (Name, Address) VALUES ('Silver Books', '338 Walnut St');
INSERT INTO Publisher (Name, Address) VALUES ('Green Media', '711 Chestnut St');
INSERT INTO Publisher (Name, Address) VALUES ('Red Media', '296 Walnut St');
INSERT INTO Publisher (Name, Address) VALUES ('Prime Media', '834 Ash St');
INSERT INTO Publisher (Name, Address) VALUES ('Sun Media', '38 Chestnut St');
INSERT INTO Publisher (Name, Address) VALUES ('Blue House', '91 Birch St');
INSERT INTO Publisher (Name, Address) VALUES ('Bright Pages', '259 Birch St');
INSERT INTO Publisher (Name, Address) VALUES ('Sun Press', '119 Walnut St');
INSERT INTO Publisher (Name, Address) VALUES ('Global Pages', '886 Ash St');
INSERT INTO Publisher (Name, Address) VALUES ('Green Press', '845 Maple St');
INSERT INTO Publisher (Name, Address) VALUES ('Silver House', '674 Ash St');
INSERT INTO Publisher (Name, Address) VALUES ('Red Works', '474 Walnut St');
INSERT INTO Publisher (Name, Address) VALUES ('Golden Media', '56 Cedar St');
INSERT INTO Publisher (Name, Address) VALUES ('Blue Works', '531 Birch St');
INSERT INTO Publisher (Name, Address) VALUES ('Global Books', '638 Chestnut St');
INSERT INTO Publisher (Name, Address) VALUES ('Green Pages', '641 Chestnut St');
INSERT INTO Publisher (Name, Address) VALUES ('Creative Works', '779 Maple St');
INSERT INTO Publisher (Name, Address) VALUES ('Sun House', '209 Elm St');
INSERT INTO Publisher (Name, Address) VALUES ('Golden Pages', '563 Pine St');
INSERT INTO Publisher (Name, Address) VALUES ('Silver Press', '950 Elm St');
INSERT INTO Publisher (Name, Address) VALUES ('Silver Pages', '449 Chestnut St');
INSERT INTO Member (FirstName, LastName, Email, phoneNumber, Address, MembershipDate, Status) VALUES ('Heidi', 'Martinez', 'heidi.martinez1@example.com', '059-982-6925', '592 Cedar St, Tel Aviv', '2025-01-10', 'expired');
INSERT INTO Member (FirstName, LastName, Email, phoneNumber, Address, MembershipDate, Status) VALUES ('Frank', 'Martin', 'frank.martin2@example.com', '054-181-4814', '888 Oak St, Ashdod', '2022-06-04', 'suspended');
INSERT INTO Member (FirstName, LastName, Email, phoneNumber, Address, MembershipDate, Status) VALUES ('Trent', 'Miller', 'trent.miller3@example.com', '055-266-7065', '364 Cedar St, Eilat', '2017-09-02', 'expired');
INSERT INTO Member (FirstName, LastName, Email, phoneNumber, Address, MembershipDate, Status) VALUES ('Trent', 'Anderson', 'trent.anderson4@example.com', '051-723-3803', '547 Cedar St, Haifa', '2020-05-10', 'suspended');
INSERT INTO Member (FirstName, LastName, Email, phoneNumber, Address, MembershipDate, Status) VALUES ('Grace', 'Thompson', 'grace.thompson5@example.com', '058-324-6313', '864 Maple St, Beer Sheva', '2016-04-28', 'active');
INSERT INTO Member (FirstName, LastName, Email, phoneNumber, Address, MembershipDate, Status) VALUES ('Ivan', 'Johnson', 'ivan.johnson6@example.com', '056-374-2084', '217 Cherry St, Beit Shemesh', '2023-02-27', 'expired');
INSERT INTO Member (FirstName, LastName, Email, phoneNumber, Address, MembershipDate, Status) VALUES ('Olivia', 'Moore', 'olivia.moore7@example.com', '056-758-8517', '147 Elm St, Haifa', '2022-10-10', 'expired');
INSERT INTO Member (FirstName, LastName, Email, phoneNumber, Address, MembershipDate, Status) VALUES ('Rupert', 'Garcia', 'rupert.garcia8@example.com', '058-369-8019', '920 Cherry St, Ashdod', '2021-06-25', 'active');
INSERT INTO Member (FirstName, LastName, Email, phoneNumber, Address, MembershipDate, Status) VALUES ('David', 'Martinez', 'david.martinez9@example.com', '058-605-2489', '774 Maple St, Tel Aviv', '2023-10-29', 'expired');
INSERT INTO Member (FirstName, LastName, Email, phoneNumber, Address, MembershipDate, Status) VALUES ('Eve', 'Johnson', 'eve.johnson10@example.com', '056-710-2040', '395 Walnut St, Tiberias', '2020-04-16', 'expired');
INSERT INTO Member (FirstName, LastName, Email, phoneNumber, Address, MembershipDate, Status) VALUES ('Grace', 'Rodriguez', 'grace.rodriguez11@example.com', '058-981-1188', '697 Oak St, Nahariya', '2017-02-13', 'suspended');
INSERT INTO Member (FirstName, LastName, Email, phoneNumber, Address, MembershipDate, Status) VALUES ('Xavier', 'Thomas', 'xavier.thomas12@example.com', '055-214-5808', '446 Pine St, Netanya', '2025-07-03', 'expired');
INSERT INTO Member (FirstName, LastName, Email, phoneNumber, Address, MembershipDate, Status) VALUES ('Walter', 'Rodriguez', 'walter.rodriguez13@example.com', '054-612-3927', '520 Oak St, Eilat', '2016-02-07', 'expired');
INSERT INTO Member (FirstName, LastName, Email, phoneNumber, Address, MembershipDate, Status) VALUES ('Olivia', 'White', 'olivia.white14@example.com', '059-303-3504', '383 Pine St, Nahariya', '2016-10-22', 'expired');
INSERT INTO Member (FirstName, LastName, Email, phoneNumber, Address, MembershipDate, Status) VALUES ('Alice', 'Smith', 'alice.smith15@example.com', '059-431-9005', '20 Oak St, Beit Shemesh', '2015-09-08', 'suspended');
INSERT INTO Member (FirstName, LastName, Email, phoneNumber, Address, MembershipDate, Status) VALUES ('Grace', 'Williams', 'grace.williams16@example.com', '050-346-2290', '88 Chestnut St, Tel Aviv', '2017-01-04', 'expired');
INSERT INTO Member (FirstName, LastName, Email, phoneNumber, Address, MembershipDate, Status) VALUES ('Xavier', 'Taylor', 'xavier.taylor17@example.com', '052-231-8787', '970 Ash St, Haifa', '2022-07-27', 'expired');
INSERT INTO Member (FirstName, LastName, Email, phoneNumber, Address, MembershipDate, Status) VALUES ('Sybil', 'Martinez', 'sybil.martinez18@example.com', '056-316-9835', '774 Cedar St, Eilat', '2021-01-24', 'expired');
INSERT INTO Member (FirstName, LastName, Email, phoneNumber, Address, MembershipDate, Status) VALUES ('Trent', 'Taylor', 'trent.taylor19@example.com', '055-548-9479', '463 Oak St, Beer Sheva', '2023-01-08', 'active');
INSERT INTO Member (FirstName, LastName, Email, phoneNumber, Address, MembershipDate, Status) VALUES ('Ivan', 'Thomas', 'ivan.thomas20@example.com', '050-702-4770', '603 Cedar St, Jerusalem', '2024-09-29', 'expired');
INSERT INTO Member (FirstName, LastName, Email, phoneNumber, Address, MembershipDate, Status) VALUES ('Trent', 'Brown', 'trent.brown21@example.com', '050-334-2104', '928 Maple St, Beit Shemesh', '2024-09-29', 'expired');
INSERT INTO Member (FirstName, LastName, Email, phoneNumber, Address, MembershipDate, Status) VALUES ('Grace', 'Johnson', 'grace.johnson22@example.com', '054-785-8953', '220 Ash St, Haifa', '2017-06-06', 'expired');
INSERT INTO Member (FirstName, LastName, Email, phoneNumber, Address, MembershipDate, Status) VALUES ('Rupert', 'Moore', 'rupert.moore23@example.com', '057-348-8749', '827 Walnut St, Beer Sheva', '2024-06-25', 'active');
INSERT INTO Member (FirstName, LastName, Email, phoneNumber, Address, MembershipDate, Status) VALUES ('Trent', 'Jackson', 'trent.jackson24@example.com', '056-462-7939', '421 Chestnut St, Jerusalem', '2017-12-27', 'expired');
INSERT INTO Member (FirstName, LastName, Email, phoneNumber, Address, MembershipDate, Status) VALUES ('Trent', 'Martinez', 'trent.martinez25@example.com', '051-162-7596', '746 Birch St, Tel Aviv', '2022-10-02', 'active');
INSERT INTO Member (FirstName, LastName, Email, phoneNumber, Address, MembershipDate, Status) VALUES ('Eve', 'Jackson', 'eve.jackson26@example.com', '058-559-3296', '433 Pine St, Eilat', '2020-05-09', 'active');
INSERT INTO Member (FirstName, LastName, Email, phoneNumber, Address, MembershipDate, Status) VALUES ('Bob', 'Thompson', 'bob.thompson27@example.com', '057-927-2604', '52 Ash St, Jerusalem', '2024-06-29', 'active');
INSERT INTO Member (FirstName, LastName, Email, phoneNumber, Address, MembershipDate, Status) VALUES ('Eve', 'Miller', 'eve.miller28@example.com', '056-597-8886', '219 Walnut St, Jerusalem', '2023-09-11', 'suspended');
INSERT INTO Member (FirstName, LastName, Email, phoneNumber, Address, MembershipDate, Status) VALUES ('Alice', 'Johnson', 'alice.johnson29@example.com', '056-371-8454', '293 Walnut St, Nahariya', '2018-02-12', 'expired');
INSERT INTO Member (FirstName, LastName, Email, phoneNumber, Address, MembershipDate, Status) VALUES ('Olivia', 'Wilson', 'olivia.wilson30@example.com', '052-294-5861', '223 Maple St, Tiberias', '2017-04-16', 'expired');
INSERT INTO Librarian (Username, PasswordHash, FirstName, LastName, Role) VALUES ('bobanderson96', 'hash51104', 'Bob', 'Anderson', 'Manager');
INSERT INTO Librarian (Username, PasswordHash, FirstName, LastName, Role) VALUES ('bobmiller75', 'hash72493', 'Bob', 'Miller', 'Supervisor');
INSERT INTO Librarian (Username, PasswordHash, FirstName, LastName, Role) VALUES ('peggyanderson21', 'hash17455', 'Peggy', 'Anderson', 'Supervisor');
INSERT INTO Librarian (Username, PasswordHash, FirstName, LastName, Role) VALUES ('caroljohnson24', 'hash18981', 'Carol', 'Johnson', 'Supervisor');
INSERT INTO Librarian (Username, PasswordHash, FirstName, LastName, Role) VALUES ('bobhernandez87', 'hash40828', 'Bob', 'Hernandez', 'Clerk');
INSERT INTO Librarian (Username, PasswordHash, FirstName, LastName, Role) VALUES ('davidjohnson73', 'hash42271', 'David', 'Johnson', 'Supervisor');
INSERT INTO Librarian (Username, PasswordHash, FirstName, LastName, Role) VALUES ('sybiljones6', 'hash91183', 'Sybil', 'Jones', 'Manager');
INSERT INTO Librarian (Username, PasswordHash, FirstName, LastName, Role) VALUES ('malloryhernandez85', 'hash86503', 'Mallory', 'Hernandez', 'Supervisor');
INSERT INTO Librarian (Username, PasswordHash, FirstName, LastName, Role) VALUES ('peggygarcia41', 'hash44179', 'Peggy', 'Garcia', 'Assistant');
INSERT INTO Librarian (Username, PasswordHash, FirstName, LastName, Role) VALUES ('victorwilliams92', 'hash51180', 'Victor', 'Williams', 'Assistant');
INSERT INTO Librarian (Username, PasswordHash, FirstName, LastName, Role) VALUES ('gracemoore51', 'hash27154', 'Grace', 'Moore', 'Intern');
INSERT INTO Librarian (Username, PasswordHash, FirstName, LastName, Role) VALUES ('niajhernandez41', 'hash19508', 'Niaj', 'Hernandez', 'Manager');
INSERT INTO Librarian (Username, PasswordHash, FirstName, LastName, Role) VALUES ('niajhernandez80', 'hash83792', 'Niaj', 'Hernandez', 'Manager');
INSERT INTO Librarian (Username, PasswordHash, FirstName, LastName, Role) VALUES ('bobjackson69', 'hash37938', 'Bob', 'Jackson', 'Supervisor');
INSERT INTO Librarian (Username, PasswordHash, FirstName, LastName, Role) VALUES ('gracemoore17', 'hash55745', 'Grace', 'Moore', 'Manager');
INSERT INTO Librarian (Username, PasswordHash, FirstName, LastName, Role) VALUES ('gracemiller48', 'hash47353', 'Grace', 'Miller', 'Assistant');
INSERT INTO Librarian (Username, PasswordHash, FirstName, LastName, Role) VALUES ('niajjones70', 'hash49651', 'Niaj', 'Jones', 'Supervisor');
INSERT INTO Librarian (Username, PasswordHash, FirstName, LastName, Role) VALUES ('trenthernandez68', 'hash11025', 'Trent', 'Hernandez', 'Supervisor');
INSERT INTO Librarian (Username, PasswordHash, FirstName, LastName, Role) VALUES ('heidithomas85', 'hash23577', 'Heidi', 'Thomas', 'Assistant');
INSERT INTO Librarian (Username, PasswordHash, FirstName, LastName, Role) VALUES ('gracemoore15', 'hash24029', 'Grace', 'Moore', 'Supervisor');
INSERT INTO Librarian (Username, PasswordHash, FirstName, LastName, Role) VALUES ('davidwhite35', 'hash46930', 'David', 'White', 'Supervisor');
INSERT INTO Librarian (Username, PasswordHash, FirstName, LastName, Role) VALUES ('frankgarcia92', 'hash54942', 'Frank', 'Garcia', 'Assistant');
INSERT INTO Librarian (Username, PasswordHash, FirstName, LastName, Role) VALUES ('victoranderson82', 'hash44600', 'Victor', 'Anderson', 'Supervisor');
INSERT INTO Librarian (Username, PasswordHash, FirstName, LastName, Role) VALUES ('oliviamartinez33', 'hash16658', 'Olivia', 'Martinez', 'Manager');
INSERT INTO Librarian (Username, PasswordHash, FirstName, LastName, Role) VALUES ('trentjones55', 'hash46265', 'Trent', 'Jones', 'Manager');
INSERT INTO Librarian (Username, PasswordHash, FirstName, LastName, Role) VALUES ('alicejohnson43', 'hash27146', 'Alice', 'Johnson', 'Intern');
INSERT INTO Librarian (Username, PasswordHash, FirstName, LastName, Role) VALUES ('evewilliams95', 'hash67912', 'Eve', 'Williams', 'Supervisor');
INSERT INTO Librarian (Username, PasswordHash, FirstName, LastName, Role) VALUES ('walterjohnson55', 'hash83519', 'Walter', 'Johnson', 'Manager');
INSERT INTO Librarian (Username, PasswordHash, FirstName, LastName, Role) VALUES ('caroljackson10', 'hash29536', 'Carol', 'Jackson', 'Supervisor');
INSERT INTO Librarian (Username, PasswordHash, FirstName, LastName, Role) VALUES ('alicethompson48', 'hash86350', 'Alice', 'Thompson', 'Supervisor');
INSERT INTO Book (Title, ISBN, PublicationYear, TotalCopies) VALUES ('To Kill a Mockingbird', '978-0-06-112008-4', 1960, 1);
INSERT INTO BookAuthor (BookID, AuthorID) VALUES (1, 1);
INSERT INTO Book (Title, ISBN, PublicationYear, TotalCopies) VALUES ('1984', '978-0-452-28423-4', 1949, 3);
INSERT INTO BookAuthor (BookID, AuthorID) VALUES (2, 2);
INSERT INTO Book (Title, ISBN, PublicationYear, TotalCopies) VALUES ('Pride and Prejudice', '978-1-85326-000-1', 1813, 3);
INSERT INTO BookAuthor (BookID, AuthorID) VALUES (3, 3);
INSERT INTO Book (Title, ISBN, PublicationYear, TotalCopies) VALUES ('The Great Gatsby', '978-0-7432-7356-5', 1925, 5);
INSERT INTO BookAuthor (BookID, AuthorID) VALUES (4, 4);
INSERT INTO Book (Title, ISBN, PublicationYear, TotalCopies) VALUES ('Moby-Dick', '978-0-14-243724-7', 1851, 5);
INSERT INTO BookAuthor (BookID, AuthorID) VALUES (5, 5);
INSERT INTO Book (Title, ISBN, PublicationYear, TotalCopies) VALUES ('War and Peace', '978-0-14-044793-4', 1869, 4);
INSERT INTO BookAuthor (BookID, AuthorID) VALUES (6, 6);
INSERT INTO Book (Title, ISBN, PublicationYear, TotalCopies) VALUES ('The Hobbit', '978-0-618-00221-3', 1937, 2);
INSERT INTO BookAuthor (BookID, AuthorID) VALUES (7, 7);
INSERT INTO Book (Title, ISBN, PublicationYear, TotalCopies) VALUES ('Harry Potter and the Sorcerers Stone', '978-0-590-35340-3', 1997, 4);
INSERT INTO BookAuthor (BookID, AuthorID) VALUES (8, 8);
INSERT INTO Book (Title, ISBN, PublicationYear, TotalCopies) VALUES ('Harry Potter and the Chamber of Secrets', '978-0-7475-3849-2', 1998, 5);
INSERT INTO BookAuthor (BookID, AuthorID) VALUES (9, 8);
INSERT INTO Book (Title, ISBN, PublicationYear, TotalCopies) VALUES ('The Da Vinci Code', '978-0-385-50420-1', 2003, 4);
INSERT INTO BookAuthor (BookID, AuthorID) VALUES (10, 9);
INSERT INTO Book (Title, ISBN, PublicationYear, TotalCopies) VALUES ('The Girl with the Dragon Tattoo', '978-0-307-45454-6', 2005, 3);
INSERT INTO BookAuthor (BookID, AuthorID) VALUES (11, 10);
INSERT INTO Book (Title, ISBN, PublicationYear, TotalCopies) VALUES ('The Girl Who Played with Fire', '978-0-307-45455-3', 2006, 3);
INSERT INTO BookAuthor (BookID, AuthorID) VALUES (12, 10);
INSERT INTO Book (Title, ISBN, PublicationYear, TotalCopies) VALUES ('Good Omens', '978-0-575-04800-1', 1990, 5);
INSERT INTO BookAuthor (BookID, AuthorID) VALUES (13, 11);
INSERT INTO BookAuthor (BookID, AuthorID) VALUES (13, 12);
INSERT INTO Book (Title, ISBN, PublicationYear, TotalCopies) VALUES ('The Talisman', '978-0-553-27297-1', 1984, 5);
INSERT INTO BookAuthor (BookID, AuthorID) VALUES (14, 13);
INSERT INTO BookAuthor (BookID, AuthorID) VALUES (14, 14);
INSERT INTO Book (Title, ISBN, PublicationYear, TotalCopies) VALUES ('The Shining', '978-0-385-12167-5', 1977, 4);
INSERT INTO BookAuthor (BookID, AuthorID) VALUES (15, 13);
INSERT INTO Book (Title, ISBN, PublicationYear, TotalCopies) VALUES ('The Stand', '978-0-385-12168-2', 1978, 4);
INSERT INTO BookAuthor (BookID, AuthorID) VALUES (16, 13);
INSERT INTO Book (Title, ISBN, PublicationYear, TotalCopies) VALUES ('A Game of Thrones', '978-0-553-10354-0', 1996, 3);
INSERT INTO BookAuthor (BookID, AuthorID) VALUES (17, 15);
INSERT INTO Book (Title, ISBN, PublicationYear, TotalCopies) VALUES ('A Clash of Kings', '978-0-553-10803-3', 1998, 2);
INSERT INTO BookAuthor (BookID, AuthorID) VALUES (18, 15);
INSERT INTO Book (Title, ISBN, PublicationYear, TotalCopies) VALUES ('The Fault in Our Stars', '978-0-525-47881-2', 2012, 2);
INSERT INTO BookAuthor (BookID, AuthorID) VALUES (19, 16);
INSERT INTO Book (Title, ISBN, PublicationYear, TotalCopies) VALUES ('The Kite Runner', '978-1-59448-000-3', 2003, 5);
INSERT INTO BookAuthor (BookID, AuthorID) VALUES (20, 17);
INSERT INTO Book (Title, ISBN, PublicationYear, TotalCopies) VALUES ('The Book Thief', '978-0-375-87302-9', 2005, 4);
INSERT INTO BookAuthor (BookID, AuthorID) VALUES (21, 18);
INSERT INTO Book (Title, ISBN, PublicationYear, TotalCopies) VALUES ('Gone Girl', '978-0-399-58072-7', 2012, 2);
INSERT INTO BookAuthor (BookID, AuthorID) VALUES (22, 19);
INSERT INTO Book (Title, ISBN, PublicationYear, TotalCopies) VALUES ('The Hunger Games', '978-0-439-02348-1', 2008, 4);
INSERT INTO BookAuthor (BookID, AuthorID) VALUES (23, 20);
INSERT INTO Book (Title, ISBN, PublicationYear, TotalCopies) VALUES ('Catching Fire', '978-0-439-02349-8', 2009, 1);
INSERT INTO BookAuthor (BookID, AuthorID) VALUES (24, 20);
INSERT INTO Book (Title, ISBN, PublicationYear, TotalCopies) VALUES ('Mockingjay', '978-0-439-02350-4', 2010, 3);
INSERT INTO BookAuthor (BookID, AuthorID) VALUES (25, 20);
INSERT INTO Book (Title, ISBN, PublicationYear, TotalCopies) VALUES ('The Lion, the Witch and the Wardrobe', '978-0-00-711397-0', 1950, 4);
INSERT INTO BookAuthor (BookID, AuthorID) VALUES (26, 21);
INSERT INTO Book (Title, ISBN, PublicationYear, TotalCopies) VALUES ('Prince Caspian', '978-0-00-711401-4', 1951, 4);
INSERT INTO BookAuthor (BookID, AuthorID) VALUES (27, 21);
INSERT INTO Book (Title, ISBN, PublicationYear, TotalCopies) VALUES ('The Girl on the Train', '978-0-316-26923-8', 2015, 4);
INSERT INTO BookAuthor (BookID, AuthorID) VALUES (28, 22);
INSERT INTO Book (Title, ISBN, PublicationYear, TotalCopies) VALUES ('The Catcher in the Rye', '978-0-316-76948-0', 1951, 2);
INSERT INTO BookAuthor (BookID, AuthorID) VALUES (29, 23);
INSERT INTO Book (Title, ISBN, PublicationYear, TotalCopies) VALUES ('Brave New World', '978-0-06-085052-4', 1932, 4);
INSERT INTO BookGenre (BookID, GenreID) VALUES (1, 4);
INSERT INTO BookGenre (BookID, GenreID) VALUES (2, 25);
INSERT INTO BookGenre (BookID, GenreID) VALUES (3, 14);
INSERT INTO BookGenre (BookID, GenreID) VALUES (4, 8);
INSERT INTO BookGenre (BookID, GenreID) VALUES (5, 6);
INSERT INTO BookGenre (BookID, GenreID) VALUES (6, 26);
INSERT INTO BookGenre (BookID, GenreID) VALUES (7, 23);
INSERT INTO BookGenre (BookID, GenreID) VALUES (8, 17);
INSERT INTO BookGenre (BookID, GenreID) VALUES (9, 15);
INSERT INTO BookGenre (BookID, GenreID) VALUES (10, 2);
INSERT INTO BookGenre (BookID, GenreID) VALUES (11, 18);
INSERT INTO BookGenre (BookID, GenreID) VALUES (12, 8);
INSERT INTO BookGenre (BookID, GenreID) VALUES (13, 30);
INSERT INTO BookGenre (BookID, GenreID) VALUES (14, 28);
INSERT INTO BookGenre (BookID, GenreID) VALUES (15, 4);
INSERT INTO BookGenre (BookID, GenreID) VALUES (16, 15);
INSERT INTO BookGenre (BookID, GenreID) VALUES (17, 5);
INSERT INTO BookGenre (BookID, GenreID) VALUES (18, 26);
INSERT INTO BookGenre (BookID, GenreID) VALUES (19, 15);
INSERT INTO BookGenre (BookID, GenreID) VALUES (20, 22);
INSERT INTO BookGenre (BookID, GenreID) VALUES (21, 17);
INSERT INTO BookGenre (BookID, GenreID) VALUES (22, 18);
INSERT INTO BookGenre (BookID, GenreID) VALUES (23, 20);
INSERT INTO BookGenre (BookID, GenreID) VALUES (24, 11);
INSERT INTO BookGenre (BookID, GenreID) VALUES (25, 25);
INSERT INTO BookGenre (BookID, GenreID) VALUES (26, 29);
INSERT INTO BookGenre (BookID, GenreID) VALUES (27, 15);
INSERT INTO BookGenre (BookID, GenreID) VALUES (28, 20);
INSERT INTO BookGenre (BookID, GenreID) VALUES (29, 27);
INSERT INTO BookGenre (BookID, GenreID) VALUES (30, 24);
INSERT INTO BookGenre (BookID, GenreID) VALUES (29, 17);
INSERT INTO BookGenre (BookID, GenreID) VALUES (14, 27);
INSERT INTO BookGenre (BookID, GenreID) VALUES (30, 18);
INSERT INTO BookGenre (BookID, GenreID) VALUES (15, 29);
INSERT INTO BookGenre (BookID, GenreID) VALUES (6, 24);
INSERT INTO BookGenre (BookID, GenreID) VALUES (28, 16);
INSERT INTO BookGenre (BookID, GenreID) VALUES (15, 9);
INSERT INTO BookGenre (BookID, GenreID) VALUES (25, 8);
INSERT INTO BookGenre (BookID, GenreID) VALUES (27, 21);
INSERT INTO BookGenre (BookID, GenreID) VALUES (9, 25);
INSERT INTO BookGenre (BookID, GenreID) VALUES (25, 17);
INSERT INTO BookGenre (BookID, GenreID) VALUES (16, 21);
INSERT INTO BookGenre (BookID, GenreID) VALUES (8, 9);
INSERT INTO BookGenre (BookID, GenreID) VALUES (15, 3);
INSERT INTO BookGenre (BookID, GenreID) VALUES (23, 10);
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (1, 'BC001000', 'on loan');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (1, 'BC001001', 'reserved');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (1, 'BC001002', 'reserved');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (2, 'BC002000', 'reserved');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (2, 'BC002001', 'available');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (3, 'BC003000', 'on loan');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (4, 'BC004000', 'on loan');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (4, 'BC004001', 'on loan');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (4, 'BC004002', 'lost');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (4, 'BC004003', 'on loan');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (5, 'BC005000', 'on loan');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (5, 'BC005001', 'available');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (5, 'BC005002', 'lost');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (5, 'BC005003', 'lost');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (6, 'BC006000', 'reserved');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (6, 'BC006001', 'lost');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (7, 'BC007000', 'lost');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (7, 'BC007001', 'available');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (8, 'BC008000', 'on loan');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (8, 'BC008001', 'lost');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (8, 'BC008002', 'lost');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (9, 'BC009000', 'available');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (9, 'BC009001', 'lost');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (9, 'BC009002', 'lost');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (10, 'BC010000', 'available');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (10, 'BC010001', 'reserved');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (10, 'BC010002', 'reserved');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (10, 'BC010003', 'lost');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (11, 'BC011000', 'lost');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (11, 'BC011001', 'on loan');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (11, 'BC011002', 'lost');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (12, 'BC012000', 'on loan');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (12, 'BC012001', 'reserved');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (12, 'BC012002', 'lost');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (13, 'BC013000', 'lost');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (13, 'BC013001', 'available');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (13, 'BC013002', 'lost');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (14, 'BC014000', 'reserved');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (14, 'BC014001', 'lost');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (14, 'BC014002', 'on loan');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (14, 'BC014003', 'lost');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (14, 'BC014004', 'on loan');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (15, 'BC015000', 'available');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (15, 'BC015001', 'lost');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (15, 'BC015002', 'available');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (16, 'BC016000', 'available');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (17, 'BC017000', 'lost');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (17, 'BC017001', 'on loan');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (18, 'BC018000', 'lost');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (18, 'BC018001', 'on loan');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (18, 'BC018002', 'available');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (18, 'BC018003', 'reserved');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (19, 'BC019000', 'lost');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (19, 'BC019001', 'reserved');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (19, 'BC019002', 'on loan');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (19, 'BC019003', 'lost');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (19, 'BC019004', 'reserved');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (20, 'BC020000', 'reserved');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (20, 'BC020001', 'lost');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (20, 'BC020002', 'reserved');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (21, 'BC021000', 'lost');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (21, 'BC021001', 'reserved');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (21, 'BC021002', 'available');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (22, 'BC022000', 'lost');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (23, 'BC023000', 'available');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (23, 'BC023001', 'available');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (23, 'BC023002', 'reserved');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (23, 'BC023003', 'on loan');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (23, 'BC023004', 'available');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (24, 'BC024000', 'available');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (24, 'BC024001', 'available');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (24, 'BC024002', 'on loan');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (25, 'BC025000', 'on loan');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (25, 'BC025001', 'available');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (25, 'BC025002', 'on loan');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (25, 'BC025003', 'on loan');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (25, 'BC025004', 'on loan');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (26, 'BC026000', 'lost');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (26, 'BC026001', 'available');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (26, 'BC026002', 'on loan');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (26, 'BC026003', 'lost');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (27, 'BC027000', 'reserved');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (27, 'BC027001', 'reserved');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (28, 'BC028000', 'on loan');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (28, 'BC028001', 'available');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (28, 'BC028002', 'on loan');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (29, 'BC029000', 'reserved');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (30, 'BC030000', 'available');
INSERT INTO BookCopy (BookID, Barcode, Status) VALUES (30, 'BC030001', 'available');
INSERT INTO Loan (MemberID, CopyID, LoanDate, DueDate, ReturnDate) VALUES (30, 1, '2025-02-07', '2025-02-21', '2025-03-09');
INSERT INTO Loan (MemberID, CopyID, LoanDate, DueDate, ReturnDate) VALUES (13, 2, '2024-12-25', '2025-01-08', NULL);
INSERT INTO Loan (MemberID, CopyID, LoanDate, DueDate, ReturnDate) VALUES (7, 3, '2025-06-08', '2025-06-22', '2025-07-05');
INSERT INTO Loan (MemberID, CopyID, LoanDate, DueDate, ReturnDate) VALUES (21, 4, '2025-03-14', '2025-03-28', '2025-04-08');
INSERT INTO Loan (MemberID, CopyID, LoanDate, DueDate, ReturnDate) VALUES (10, 5, '2024-07-31', '2024-08-14', '2024-08-04');
INSERT INTO Loan (MemberID, CopyID, LoanDate, DueDate, ReturnDate) VALUES (26, 6, '2024-09-30', '2024-10-14', NULL);
INSERT INTO Loan (MemberID, CopyID, LoanDate, DueDate, ReturnDate) VALUES (12, 7, '2024-10-17', '2024-10-31', '2024-10-29');
INSERT INTO Loan (MemberID, CopyID, LoanDate, DueDate, ReturnDate) VALUES (3, 8, '2024-10-30', '2024-11-13', '2024-10-31');
INSERT INTO Loan (MemberID, CopyID, LoanDate, DueDate, ReturnDate) VALUES (28, 9, '2024-12-13', '2024-12-27', NULL);
INSERT INTO Loan (MemberID, CopyID, LoanDate, DueDate, ReturnDate) VALUES (4, 10, '2024-12-07', '2024-12-21', NULL);
INSERT INTO Loan (MemberID, CopyID, LoanDate, DueDate, ReturnDate) VALUES (21, 11, '2024-11-23', '2024-12-07', NULL);
INSERT INTO Loan (MemberID, CopyID, LoanDate, DueDate, ReturnDate) VALUES (14, 12, '2025-04-17', '2025-05-01', NULL);
INSERT INTO Loan (MemberID, CopyID, LoanDate, DueDate, ReturnDate) VALUES (21, 13, '2025-02-28', '2025-03-14', '2025-03-30');
INSERT INTO Loan (MemberID, CopyID, LoanDate, DueDate, ReturnDate) VALUES (18, 14, '2024-11-11', '2024-11-25', '2024-12-08');
INSERT INTO Loan (MemberID, CopyID, LoanDate, DueDate, ReturnDate) VALUES (24, 15, '2024-09-16', '2024-09-30', '2024-10-14');
INSERT INTO Loan (MemberID, CopyID, LoanDate, DueDate, ReturnDate) VALUES (8, 16, '2025-06-02', '2025-06-16', '2025-06-17');
INSERT INTO Loan (MemberID, CopyID, LoanDate, DueDate, ReturnDate) VALUES (8, 17, '2024-11-21', '2024-12-05', '2024-12-13');
INSERT INTO Loan (MemberID, CopyID, LoanDate, DueDate, ReturnDate) VALUES (13, 18, '2025-01-25', '2025-02-08', '2025-02-22');
INSERT INTO Loan (MemberID, CopyID, LoanDate, DueDate, ReturnDate) VALUES (11, 19, '2025-04-14', '2025-04-28', '2025-04-26');
INSERT INTO Loan (MemberID, CopyID, LoanDate, DueDate, ReturnDate) VALUES (26, 20, '2025-03-06', '2025-03-20', '2025-04-04');
INSERT INTO Loan (MemberID, CopyID, LoanDate, DueDate, ReturnDate) VALUES (20, 21, '2024-07-22', '2024-08-05', NULL);
INSERT INTO Loan (MemberID, CopyID, LoanDate, DueDate, ReturnDate) VALUES (18, 22, '2025-07-11', '2025-07-25', '2025-07-18');
INSERT INTO Loan (MemberID, CopyID, LoanDate, DueDate, ReturnDate) VALUES (3, 23, '2025-03-15', '2025-03-29', NULL);
INSERT INTO Loan (MemberID, CopyID, LoanDate, DueDate, ReturnDate) VALUES (16, 24, '2024-10-05', '2024-10-19', NULL);
INSERT INTO Loan (MemberID, CopyID, LoanDate, DueDate, ReturnDate) VALUES (23, 25, '2024-11-15', '2024-11-29', '2024-12-01');
INSERT INTO Loan (MemberID, CopyID, LoanDate, DueDate, ReturnDate) VALUES (15, 26, '2025-07-08', '2025-07-22', '2025-07-16');
INSERT INTO Loan (MemberID, CopyID, LoanDate, DueDate, ReturnDate) VALUES (13, 27, '2024-07-27', '2024-08-10', '2024-08-18');
INSERT INTO Loan (MemberID, CopyID, LoanDate, DueDate, ReturnDate) VALUES (19, 28, '2025-01-09', '2025-01-23', '2025-01-26');
INSERT INTO Loan (MemberID, CopyID, LoanDate, DueDate, ReturnDate) VALUES (12, 29, '2024-12-11', '2024-12-25', NULL);
INSERT INTO Loan (MemberID, CopyID, LoanDate, DueDate, ReturnDate) VALUES (18, 30, '2025-01-28', '2025-02-11', '2025-02-12');
INSERT INTO Reservation (MemberID, BookID, ReservationDate, Status) VALUES (9, 10, '2025-03-10', 'active');
INSERT INTO Reservation (MemberID, BookID, ReservationDate, Status) VALUES (4, 24, '2025-04-09', 'completed');
INSERT INTO Reservation (MemberID, BookID, ReservationDate, Status) VALUES (4, 24, '2024-10-15', 'cancelled');
INSERT INTO Reservation (MemberID, BookID, ReservationDate, Status) VALUES (6, 7, '2025-03-28', 'cancelled');
INSERT INTO Reservation (MemberID, BookID, ReservationDate, Status) VALUES (16, 9, '2024-09-18', 'cancelled');
INSERT INTO Reservation (MemberID, BookID, ReservationDate, Status) VALUES (20, 10, '2025-05-26', 'active');
INSERT INTO Reservation (MemberID, BookID, ReservationDate, Status) VALUES (10, 8, '2025-01-13', 'active');
INSERT INTO Reservation (MemberID, BookID, ReservationDate, Status) VALUES (10, 1, '2024-07-19', 'cancelled');
INSERT INTO Reservation (MemberID, BookID, ReservationDate, Status) VALUES (5, 9, '2025-06-23', 'active');
INSERT INTO Reservation (MemberID, BookID, ReservationDate, Status) VALUES (18, 10, '2024-07-24', 'active');
INSERT INTO Reservation (MemberID, BookID, ReservationDate, Status) VALUES (21, 28, '2024-11-07', 'active');
INSERT INTO Reservation (MemberID, BookID, ReservationDate, Status) VALUES (28, 1, '2024-09-26', 'completed');
INSERT INTO Reservation (MemberID, BookID, ReservationDate, Status) VALUES (16, 16, '2024-12-03', 'completed');
INSERT INTO Reservation (MemberID, BookID, ReservationDate, Status) VALUES (6, 2, '2025-03-09', 'completed');
INSERT INTO Reservation (MemberID, BookID, ReservationDate, Status) VALUES (4, 27, '2025-06-13', 'completed');
INSERT INTO Reservation (MemberID, BookID, ReservationDate, Status) VALUES (16, 3, '2024-09-24', 'cancelled');
INSERT INTO Reservation (MemberID, BookID, ReservationDate, Status) VALUES (22, 2, '2025-04-30', 'active');
INSERT INTO Reservation (MemberID, BookID, ReservationDate, Status) VALUES (26, 19, '2025-02-11', 'active');
INSERT INTO Reservation (MemberID, BookID, ReservationDate, Status) VALUES (8, 4, '2024-10-04', 'completed');
INSERT INTO Reservation (MemberID, BookID, ReservationDate, Status) VALUES (20, 20, '2024-09-03', 'active');
INSERT INTO Reservation (MemberID, BookID, ReservationDate, Status) VALUES (25, 17, '2025-01-03', 'completed');
INSERT INTO Reservation (MemberID, BookID, ReservationDate, Status) VALUES (30, 15, '2025-02-14', 'cancelled');
INSERT INTO Reservation (MemberID, BookID, ReservationDate, Status) VALUES (14, 10, '2024-09-28', 'cancelled');
INSERT INTO Reservation (MemberID, BookID, ReservationDate, Status) VALUES (2, 20, '2025-05-27', 'active');
INSERT INTO Reservation (MemberID, BookID, ReservationDate, Status) VALUES (21, 7, '2025-03-03', 'cancelled');
INSERT INTO Reservation (MemberID, BookID, ReservationDate, Status) VALUES (3, 6, '2025-03-16', 'active');
INSERT INTO Reservation (MemberID, BookID, ReservationDate, Status) VALUES (18, 3, '2025-04-27', 'active');
INSERT INTO Reservation (MemberID, BookID, ReservationDate, Status) VALUES (14, 15, '2024-07-29', 'cancelled');
INSERT INTO Reservation (MemberID, BookID, ReservationDate, Status) VALUES (16, 10, '2025-06-30', 'active');
INSERT INTO Reservation (MemberID, BookID, ReservationDate, Status) VALUES (10, 23, '2025-02-22', 'cancelled');
INSERT INTO Fine (LoanID, Amount, PaidDate) VALUES (1, 25.93, '2025-03-12');
INSERT INTO Fine (LoanID, Amount, PaidDate) VALUES (2, 20.93, NULL);
INSERT INTO Fine (LoanID, Amount, PaidDate) VALUES (3, 27.79, '2025-07-31');
INSERT INTO Fine (LoanID, Amount, PaidDate) VALUES (4, 23.95, '2025-04-27');
INSERT INTO Fine (LoanID, Amount, PaidDate) VALUES (5, 20.17, '2024-09-03');
INSERT INTO Fine (LoanID, Amount, PaidDate) VALUES (6, 6.74, NULL);
INSERT INTO Fine (LoanID, Amount, PaidDate) VALUES (7, 4.33, '2024-11-06');
INSERT INTO Fine (LoanID, Amount, PaidDate) VALUES (8, 19.78, '2024-11-30');
INSERT INTO Fine (LoanID, Amount, PaidDate) VALUES (9, 8.7, NULL);
INSERT INTO Fine (LoanID, Amount, PaidDate) VALUES (10, 5.12, NULL);
INSERT INTO Fine (LoanID, Amount, PaidDate) VALUES (11, 2.73, NULL);
INSERT INTO Fine (LoanID, Amount, PaidDate) VALUES (12, 23.99, NULL);
INSERT INTO Fine (LoanID, Amount, PaidDate) VALUES (13, 18.26, '2025-04-26');
INSERT INTO Fine (LoanID, Amount, PaidDate) VALUES (14, 17.51, '2024-12-18');
INSERT INTO Fine (LoanID, Amount, PaidDate) VALUES (15, 13.74, '2024-10-29');
INSERT INTO Fine (LoanID, Amount, PaidDate) VALUES (16, 20.97, '2025-07-10');
INSERT INTO Fine (LoanID, Amount, PaidDate) VALUES (17, 12.67, '2024-12-22');
INSERT INTO Fine (LoanID, Amount, PaidDate) VALUES (18, 15.51, '2025-03-10');
INSERT INTO Fine (LoanID, Amount, PaidDate) VALUES (19, 13.7, '2025-05-16');
INSERT INTO Fine (LoanID, Amount, PaidDate) VALUES (20, 2.16, '2025-04-18');
INSERT INTO Fine (LoanID, Amount, PaidDate) VALUES (21, 22.3, NULL);
INSERT INTO Fine (LoanID, Amount, PaidDate) VALUES (22, 18.51, '2025-07-19');
INSERT INTO Fine (LoanID, Amount, PaidDate) VALUES (23, 3.65, NULL);
INSERT INTO Fine (LoanID, Amount, PaidDate) VALUES (24, 28.9, NULL);
INSERT INTO Fine (LoanID, Amount, PaidDate) VALUES (25, 25.24, '2024-12-20');
INSERT INTO Fine (LoanID, Amount, PaidDate) VALUES (26, 18.03, '2025-07-17');
INSERT INTO Fine (LoanID, Amount, PaidDate) VALUES (27, 29.99, '2024-09-09');
INSERT INTO Fine (LoanID, Amount, PaidDate) VALUES (28, 24.82, '2025-02-14');
INSERT INTO Fine (LoanID, Amount, PaidDate) VALUES (29, 2.17, NULL);
INSERT INTO Fine (LoanID, Amount, PaidDate) VALUES (30, 22.93, '2025-02-28');